import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Gym Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className=" py-6 px-5 bg-slate-200 flex justify-center gap-5 h-auto max-w-screen-2xl mx-auto">
                <main className={inter.className}>{children}</main>
            </body>
        </html>
    );
}
